apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: wpd
  name: wpd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wpd
  template:
    metadata:
      labels:
        app: wpd
    spec:
      containers:
      - image: wordpress:5.1.1-php7.3-apache
        name: wordpress
