apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: wpd
    app.kubernetes.io/managed-by: Helm
  name: wpd
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: wpd
  type: NodePort
status:
  loadBalancer: {}
